const readline = require("readline").createInterface({
  input: process.stdin,
  output: process.stdout,
});
/*
We will create an application where we will register people into an array. 
We will have a functionat that allows the host to check the registry to see all the user registered.
Use a for loop to go through all the users registered

This application also allows the host add users to the banned list and check them when they need to

CHALLENGE, when adding a user, if the user exist in the ban list, do not add the user
- hint, you will need a boolean to check... let checkBan = false...

CHALLENGE 2, use the settings to allow the adding the go through or not
*/

/* 
declare the user base with names generated by chat-gpt
user a high number of names so a small portion can be used for the banned list
keep the captialziation consistant with the variables, functions, and commands
making canceling the command request easy, make the ban-commands use specefic input to run their functions
*/
let users = ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Hannah", "Isaac", "Jack",
    "Karen", "Liam", "Mia", "Noah", "Olivia", "Peter", "Quinn", "Rachel", "Sam", "Tina",
    "Uma", "Victor", "Wendy", "Xander", "Yara", "Zane", "Alex", "Bella", "Chris", "Diana",
    "Evan", "Fiona", "George", "Harry", "Ivy", "James", "Katie", "Leo", "Mason", "Nina",
    "Owen", "Paula", "Quincy", "Ruth", "Sean", "Tara", "Ulysses", "Violet", "William", "Xena",
    "Yvonne", "Zach", "Aaron", "Beth", "Cody", "Daisy", "Elliot", "Faith", "Gabe", "Hazel",
    "Ian", "Jade", "Ken", "Laura", "Mark", "Nora", "Oscar", "Piper", "Quentin", "Rosie",
    "Steve", "Tracy", "Uri", "Vera", "Walter", "Ximena", "Yuri", "Zelda", "Adam", "Brenda",
    "Caleb", "Debbie", "Eddie", "Faye", "Greg", "Holly", "Iris", "Jon", "Kara", "Lucas"];

let banned = [" Miles ", " Nate ", " Opal ", " Penny ", " Ron ", " Toby ", " Ursula ", " Vivian ", " Wade ", " Xia "];
let settings = {
  addRegistry:true,
  checkRegistry:true,
  banPerson:true,
  checkBans:true,
  allowBans:true
}


/*
start with checking the setting permissions, then using the same method tought to us through readline.question ask for the name the user wants to add, the add the name and ---display the full registry--may change cause of permissons.
*/
function AddUserToRegistry() {
  //user readline to prompt for the name of the user to be added
  if(settings.addRegistry === true){
    readline.question("what is the name to add ", _user=>{
        users.push(_user);
        console.log(users);
     StartApp();
    
    })
    }
    }


/*console.log some indecation the function worked and the the names are for, then loop the arrary users and display each name in it. then ask for the next command once finshed.
*/
function CheckRegistry() {
  if(settings.checkRegistry === true){
  console.log("the Registry contains the following names:")
    for(let i=0; i<users.length; i++){
        console.log(`${users[i]}`)
    }}
    StartApp();
}

function BanUser(){
  if(settings.allowBans === true){
readline.question("who would you like to ban ", _banHammer=>{
  /* if(_banHammer === i<banned.length){
    console.log("user is already banned")
  } else */
  users.splice(_banHammer);
  banned.push(_banHammer);
  console.log(`you have banned the user ${_banHammer}`)
    StartApp();
  })
}
}

  //use readline to prompt for the name of the user to be banned



/*
loop through all the banned users and log to the console then the run the startApp function so more commands can be run
*/
function CheckBanned(){
  if(settings.checkBans === true){
  console.log(`These are the banned users: ${banned}`)
  
} StartApp();
}

/*
 add command for all requested features that will call their respective functions which when finished will call the startApp functuon again so more cammands can be run
*/
function StartApp() {
  readline.question("What would you like to do? ", (_command) => {
    
    if(_command === "BanUser-010*"){
      BanUser();

    } else if(_command === "checkBanned-010*"){
    CheckBanned();

    } else if(_command === "checkRegistry"){
      CheckRegistry();

    } else if(_command === "addUser"){
      AddUserToRegistry();

    } else if(_command === "quit", "e", "l", "q", "c", "leave", "exit", "cancel") {
      readline.close();
    }
  });
}


// Start running the script
StartApp();


/* 

His code is set up perfectly, everything looks great. If i were to suggest something, it would be to make it a little more organized. Other than that, it is good. Good job -Saahil

*/ 